### ISSUE TITLE
Provide a node buffers implementation in js

### ISSUE THREAD

**Issue by willbanks** [steembots/steemsign#2]
This issue must be completed to close #1 
This issue is a core issue.  Most of the code requires and expects so called "node buffers"
These are available under browserify, however there is no standalone "nodebuffers" file and npm or browserify are not allowed.

The best candidate is to flatten and normalize this...
https://github.com/feross/buffer/blob/master/index.js

The dependencies should be extracted into single standalone files and the index.html file should be updated to reference them.

**Comment by jtault** [comment]
I will try working on this issue and see how it goes.

**Comment by willbanks** [comment]
Excellent, keep me in the loop.

**Comment by willbanks** [comment]
How is it coming?

**Comment by jtault** [comment]
I think good. I'd like to share so you can take a look and let me know if what I've done is correct. I'm not able to push. Do I need to fork first?

**Comment by willbanks** [comment]
You should be able to push you're a member

**Comment by jtault** [comment]
Is this what my .git/config should look like?
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    url = http://github.com/steembots/steemsign.git
    fetch = +refs/heads/_:refs/remotes/origin/_
[branch "master"]
    remote = origin
    merge = refs/heads/master

I'm getting:
remote: Permission to steembots/steemsign.git denied to jtault.
fatal: unable to access 'https://github.com/steembots/steemsign.git/': The requested URL returned error: 403

**Comment by willbanks** [comment]
Strange, looks right to me, but does say unauthorized.

**Comment by willbanks** [comment]
derp!  I forgot to give the team write access to the repo.  I fixed it now.  Try again :)

**Comment by jtault** [comment]
Ok I just pushed. I'm pretty sure the dependencies are working. I tried several of the tests and they seem alright. I'm not sure about whether or not Buffer is working. I had to add "Buffer.prototype = {};" near the top of nodebuffers.js because I was getting a "Buffer.prototype is undefined" error. I'm not exactly sure how to use the Buffer, because I'm still getting a "Buffer is not a constructor" error from the steemsign.js.

**Comment by willbanks** [comment]
Alright I'll look and see what I can do about it.

**Comment by jtault** [comment]
I can start working on issue #4 if that helps.

**Comment by willbanks** [comment]
#3 Would probably be a better place to go next.

Also to answer your question on how to use buffers...
https://nodejs.org/api/buffer.html

**Comment by jtault** [comment]
Ok, I'll get started on #3.

**Comment by jtault** [comment]
Ok, seems like the Buffer might be working correctly. Just have to construct correctly.

**Comment by willbanks** [comment]
Excellent work!  I'll verify this in the next few hours.  Go ahead and start on #3

**Comment by jtault** [comment]
Actually I think I may defined Buffer as a singleton instead of a class. I'm still relatively new to JS, I will try to fix.

**Comment by jtault** [comment]
For example, the first six here seem to work, but line seven gives "Buffer is not a constructor".
    var buf1 = Buffer.alloc(10);
    var buf2 = Buffer.alloc(10, 1);
    var buf3 = Buffer.allocUnsafe(10);
    var buf4 = Buffer.from([1,2,3]);
    var buf5 = Buffer.from('test');
    var buf6 = Buffer.from('tést', 'utf8');
    var buf7 = new Buffer();
Not sure if it is critical that we can't use 'new' to construct.

EDIT: Disregard above. I fixed the Buffer definition.

**Comment by jtault** [comment]
This seems to be working. I checked about half of the tests and found no errors.
